### ISSUE TITLE
get/set map extent

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rap#11]
Is there a way to **set** map extent?

How to use the event system to **get** current map extent? There is no example, no doc and looking at the code it is not obvious.

**Comment by stundzig** [comment]
The extent can be set via the View which is passed to the OlMap constructor, https://github.com/Polymap4/polymap4-rap/blob/master/org.polymap.rap.openlayers/src/org/polymap/rap/openlayers/view/View.java

To get the current extent, i'm working on implementing the event mechanism for this attribute.

**Comment by stundzig** [comment]
The extent is currently *experimental* and its only used to constraint the center coordinate. So set/get them directly is not supported by openlayers at the moment. But there exists *JS* methods to calculate the extent. If they are needed, i'll implement a delegate method in the *View* class.

**Comment by fb71** [comment]
Egal wie, ich brauche eine Lösung. Ansonsten geht es an der Stelle bei mir nicht weiter. Das wollte ich mit dem "critical" ausdrücken.

**Comment by stundzig** [comment]
see https://github.com/Polymap4/polymap4-rap/blob/master/org.polymap.rap.openlayers/src/org/polymap/rap/openlayers/view/View.java method fit, on how to set the extent
