### ISSUE TITLE
OpenLayer CSS not loaded

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rap#13]
The demo application has hand wired code to load CSS. This is the reason why controls are not shown in any application other than the demo. Would be cool to have the CSSs loaded on-demand.

**Comment by fb71** [comment]
Trying to find a way to solve this I find that resources (CSS and JS) are loaded from absolute URL. This is bad as it prevents running the app behind a reverse proxy. We need a way to change this.

In conjunction with the above the servlet path of the demo /ol/demo is a problem because for loading resources from relative URL (for example ../olres/js) we have to make sure that web app on the same 'level' as the download URLs.

**Comment by fb71** [comment]
BTW: is there a good reason to use the ApplicationConfiguration for the demos instead of plain EntryPoint extensions?

**Comment by stundzig** [comment]
Comment 1: To support customizations of the CSS by the plugin user, i've moved the load of the css files into the demo application. So each application based on the openlayers plugin can decide to use the default css or some other customized css.

Comment 2: Ok, i'll rethink about that.

Comment 3: With application configuration, i can configure different entry points and i can easily register service handler, resources, special body.html-templates and so on. I thought it is the preferred way to configure a RAP application programmatically -> http://www.eclipse.org/rap/developers-guide/devguide.php?topic=application-configuration.html&version=3.0

**Comment by fb71** [comment]
Great! Thanks! :)
