### ISSUE TITLE
Loading animation / busy indicator

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rap#21]
A visual indicator that map is loading/rendering.

  - displayed when map/layer/tile loading takes longer than x sec.
  - removed when loading is done
  - or timeout exceeds
  
https://github.com/Polymap3/polymap3-core/blob/master/plugins/org.polymap.openlayers.rap.widget/ol_js_addins/LoadingPanel.js

**Comment by joergreichert** [comment]
In OpenLayers this is done by http://openlayers.org/en/master/apidoc/ol.source.TileEvent.html  - these events are fired by most of the sources

**Comment by joergreichert** [comment]
Here is an example usage: http://openlayers.org/en/master/examples/tile-load-events.html
