### ISSUE TITLE
Suppress rescale after resize event

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rap#36]
Currently, when the container div receives a resize event (?) the map contents is displayed rescaled before layers are refreshed. Sometimes refresh does not work (?) and map continues to display contents with wrong ratio.

For P4 (and probably any other client) the rescaling is not expected by the user at all as is displayes wrong 'projection'. It would be good to be able to skip this altogether.

**Comment by stundzig** [comment]
I can't suppress the rescale, but the refresh should now work every time. Please check it. But it seems to be not an OpenLayers 3 bug. I'll check if RAP causes this repaint/rescale.

**Comment by stundzig** [comment]
Since the rescale works correctly now, we could later try to improve the RAP div resize.
