### ISSUE TITLE
Rename OpenLayers_ -> Ol_

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rap#6]

**Comment by fb71** [comment]
Ich habs gemacht. Sieht viel besser aus. Weil sich die API ja nun sowieso von set/get auf properties ändert, müsste client code sowieso portiert werden. Soll ich das einchecken? oder übersehe ich noch was?

**Comment by stundzig** [comment]
Hi,

jo check es ein, wenn es besser aussieht. Für mich war das mit den Buildern auch eher ein Experiment, wie es sich anfühlt. Properties() gefällt mir aber auch besser.

**Comment by fb71** [comment]
commit 28e5db913cfcd6b8069de025bf20b6ebbf9ba55d
